export enum PRODUCT_TAB_KEY {
  Overview,
  Features,
  Alternatives,
  Pricing,
  Manufacturer,
}

export const SPECIFICATION_ICONS = {
  asia_icon: '/assets/icons/asia.svg',
  battery_safety_icon: '/assets/icons/battery-safety.svg',
  battery_icon: '/assets/icons/battery.svg',
  canada_icon: '/assets/icons/canada.svg',
  client_icon: '/assets/icons/client.svg',
  dimensions_icon: '/assets/icons/dimensions.svg',
  display_resolution_icon: '/assets/icons/display-resolution.svg',
  dual_sim_icon: '/assets/icons/dual-sim.svg',
  e911_icon: '/assets/icons/e911.svg',
  ethernet_ports_icon: '/assets/icons/ethernet-ports.svg',
  europe_icon: '/assets/icons/europe.svg',
  global_capable_icon: '/assets/icons/global-capable.svg',
  gnss_icon: '/assets/icons/gnss.svg',
  gps_icon: '/assets/icons/gps.svg',
  latin_america_icon: '/assets/icons/latin-america.svg',
  lte_icon: '/assets/icons/lte.svg',
  magnetic_card_icon: '/assets/icons/magnetic-card.svg',
  mexico_icon: '/assets/icons/mexico.svg',
  mms_icon: '/assets/icons/mms.svg',
  modem_icon: '/assets/icons/modem.svg',
  nat_icon: '/assets/icons/nat.svg',
  number_share_icon: '/assets/icons/number-share.svg',
  operating_system_icon: '/assets/icons/operating-system.svg',
  operating_temperature_icon: '/assets/icons/operating-temperature.svg',
  relative_humidity_icon: '/assets/icons/relative-humidity.svg',
  routing_protocols_icon: '/assets/icons/routing-protocols.svg',
  shield_protocol_icon: '/assets/icons/shield-protocol.svg',
  split_data_routing_icon: '/assets/icons/split-data-routing.svg',
  storage_temperature_icon: '/assets/icons/storage-temperature.svg',
  usb_ports_icon: 'public/assets/icons/usb_ports.svg',
  voltage_supply_icon: '/assets/icons/voltage-supply.svg',
  vpn_support_icon: '/assets/icons/vpn-support.svg',
  weight_icon: '/assets/icons/weight.svg',
  wireless_private_network_icon: '/assets/icons/wireless-private-network.svg',
  accelerometer_icon: '/assets/icons/accelerometer.svg',
  air_sensor_icon: '/assets/icons/air-sensor.svg',
};
