export const API_ENDPOINT = process.env.NEXT_PUBLIC_API_ENDPOINT;
export const BILLING_SETTINGS_URL = process.env.NEXT_PUBLIC_BILLING_SETTINGS_URL;
export const TURNSTILE_SITE_KEY = process.env.NEXT_PUBLIC_TURNSTILE_KEY || '';
